import os
import time

import dotenv
from llamacpp_client import ChatLlamaCppServer
from langchain_core.messages import SystemMessage, HumanMessage

from log import Logger


class Summarizer:
    def __init__(self, env_file="key.env"):
        """
        Initializes the Summarizer class with a specific model and configures the llama.cpp client.

        Args:
            env_file (str, optional): The environment file containing the configuration. Default is "key.env".
            model (str, optional): The model to use for summarization. If not provided, defaults to the model set in the environment.

        Attributes:
            model_alias (str): The specified model alias for llama.cpp.

        Returns:
            None

        Raises:
            KeyError: If the environment variables cannot be found.
        """
        self.logger = Logger(self.__class__.__name__).get_logger()
        dotenv.load_dotenv(env_file, override=True)
        self.model_alias = os.getenv("LLM_MODEL_ALIAS", "meta-llama-3")

    def claim_title_summarize(self, text, max_tokens=1024, temperature=0.5, stop=None):
        """
        Generates a summary for the given claim using the llama.cpp server.

        Args:
            text (str): The text to summarize.
            max_tokens (int, optional): The maximum number of tokens for the completion. Default is 1024.
            temperature (float, optional): Controls randomness. Default is 0.5.
            stop (str or None, optional): Optional sequence indicating where the model should stop. Default is None.

        Returns:
            str: The summary generated by the model.

        Raises:
            Exception: If there is an error during the summarization process.
        """
        self.logger.info("Starting summarization process.")
        self.logger.info("Input text: %s...", text[:200])

        try:
            client = ChatLlamaCppServer(
                model=self.model_alias, temperature=temperature, max_tokens=max_tokens
            )

            messages = [
                SystemMessage(
                    content="""You are an AI designed to rephrase a claim into a concise, specific, and highly searchable query. 
                                                    Focus on preserving all critical details such as names, dates, locations, or key terms, but avoid unnecessary words. 
                                                    Provide only the text without any additional formatting"""
                ),
                HumanMessage(content=text),
            ]

            response = client.invoke(messages, stop=stop)
            summary = response.content

            if summary is None:
                return None, 0

            # Normalize possible list/dict responses into a single string
            if isinstance(summary, list):
                summary = " ".join(
                    item if isinstance(item, str) else str(item) for item in summary
                )
            elif isinstance(summary, dict):
                summary = str(summary)
                # Normalize possible list/dict responses into a single string
            if isinstance(summary, list):
                summary = " ".join(
                    item if isinstance(item, str) else str(item) for item in summary
                )
            elif isinstance(summary, dict):
                summary = str(summary)

            summary = summary.strip()

            # Extract tokens if available in the response metadata
            tokens = (
                response.response_metadata.get("token_usage", {}).get("total_tokens", 0)
                if hasattr(response, "response_metadata")
                else 0
            )

            self.logger.info("Summarization completed successfully.")
            self.logger.info("Generated scraping summary: %s...", summary[:1000])

            return summary, tokens

        except Exception as e:
            self.logger.error("Error generating summary: %s", e)
            return None, 0

    def generate_summary(self, text, max_tokens=1024, temperature=0.5, stop=None):
        """
        Generates a summary for the given text using the specified model.

        Args:
            text (str): The text to be summarized.
            temperature (float): Sampling temperature (default: 0.7).
            max_tokens (int): Maximum number of tokens for the summary (default: 100).
            stop (str or list): Stop sequence(s) for the model (default: None).

        Returns:
            str: The generated summary.
        """
        client = ChatLlamaCppServer(
            model=self.model_alias, temperature=temperature, max_tokens=max_tokens
        )

        messages = [
            SystemMessage(
                content="""You are a summarizer, be specific. Don't use lists or bullet points. 
                                                Provide only the string without specifying that it is a summary.
                                                Translate in English."""
            ),
            HumanMessage(content=text),
        ]

        response = client.invoke(messages, stop=stop)
        summary = response.content
        tokens = (
            response.response_metadata.get("token_usage", {}).get("total_tokens", 0)
            if hasattr(response, "response_metadata")
            else 0
        )

        if summary is None:
            return None, 0

        if isinstance(summary, list):
            summary = " ".join(
                item if isinstance(item, str) else str(item) for item in summary
            )

        return summary.strip(), tokens

    def summarize_texts(
        self,
        texts,
        max_tokens=1024,
        temperature=0.5,
        stop=None,
        token_cut=20000,
        sleep_temperature=0.0003,
    ):
        """
        Generates summaries for a list of texts.

        Args:
            texts (list): List of strings to summarize.
            max_tokens (int, optional): Maximum number of tokens for each completion. Default is 1024.
            temperature (float, optional): Controls randomness. Default is 0.5.
            stop (str or None, optional): Optional sequence indicating where the model should stop. Default is None.

        Returns:
            list: A list of generated summaries.

        Raises:
            Exception: If there is an error during the batch summarization process.
        """
        self.logger.info(
            "Starting batch summarization process for %d texts.", len(texts)
        )
        summaries = []
        total_tokens_used = 0

        for index, text in enumerate(texts):
            self.logger.info("Summarizing text %d/%d...", index + 1, len(texts))
            self.logger.debug("Text %d content: %s", index + 1, text[:200])

            cutted_text = text[:token_cut]

            try:
                summary, tokens = self.generate_summary(
                    text=cutted_text,
                    max_tokens=max_tokens,
                    temperature=temperature,
                    stop=stop,
                )
                if summary:
                    summaries.append(summary)
                    total_tokens_used += tokens
                    self.logger.info("Text %d summarized successfully.", index + 1)
                    sleep_time = len(cutted_text) * sleep_temperature
                    self.logger.info("Sleep of %f seconds", sleep_time)
                    time.sleep(sleep_time)
                else:
                    self.logger.warning("No summary returned for text %d.", index + 1)
            except Exception as e:
                self.logger.error("Error summarizing text %d: %s", index + 1, str(e))
                summaries.append(None)

        self.logger.info("Batch summarization process completed.")
        self.logger.info("Total tokens used: %d", total_tokens_used)
        return summaries
