services:
  neo4j:
    image: neo4j:5.26.2-community-ubi9
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    command: /bin/sh -c "python init_db.py && uvicorn backend:backend_app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    environment:
      - HF_HOME=/app/hf_cache
    env_file:
      - key.env
    depends_on:
      - neo4j
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
      - hf_cache:/app/hf_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  controller:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    command: uvicorn controller:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"
    env_file:
      - key.env
    depends_on:
      - backend

  dashboard:
    build: .
    command: streamlit run Dashboard/dashboard.py --server.runOnSave=true --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - key.env
    depends_on:
      - controller
    volumes:
      - ./assets:/app/assets

volumes:
  neo4j_data:
  data:
  assets:
  hf_cache: